# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
                ('h_01', models.IntegerField(default=None)),
                ('h_02', models.IntegerField(default=None)),
                ('h_03', models.IntegerField(default=None)),
                ('h_04', models.IntegerField(default=None)),
                ('h_05', models.IntegerField(default=None)),
                ('h_06', models.IntegerField(default=None)),
                ('h_07', models.IntegerField(default=None)),
                ('h_08', models.IntegerField(default=None)),
                ('h_09', models.IntegerField(default=None)),
                ('h_10', models.IntegerField(default=None)),
                ('h_11', models.IntegerField(default=None)),
                ('h_12', models.IntegerField(default=None)),
                ('h_13', models.IntegerField(default=None)),
                ('h_14', models.IntegerField(default=None)),
                ('h_15', models.IntegerField(default=None)),
                ('h_16', models.IntegerField(default=None)),
                ('h_17', models.IntegerField(default=None)),
                ('h_18', models.IntegerField(default=None)),
                ('h_19', models.IntegerField(default=None)),
                ('h_20', models.IntegerField(default=None)),
                ('h_21', models.IntegerField(default=None)),
                ('h_22', models.IntegerField(default=None)),
                ('h_23', models.IntegerField(default=None)),
                ('h_24', models.IntegerField(default=None)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_weather_site.Service')),
            ],
        ),
    ]
