# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_weather_site', '0004_auto_20171027_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatures',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
