# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_weather_site', '0005_auto_20171101_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatures',
            name='date',
            field=models.DateField(),
        ),
    ]
