# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_weather_site', '0007_auto_20171101_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperatures',
            old_name='h_24',
            new_name='h_00',
        ),
    ]
